name: Execute script

on:
  workflow_dispatch:
    inputs:
      action:
        description: Action
        required: true
        type: choice
        options:
          - upsert
          - remove
          - disable

      plugins:
        description: Plugins
        required: true
        type: string

      channel:
        description: Patchbay channel
        required: false
        type: string

permissions:
  contents: write
  actions: read

jobs:
  execute:
    name: ${{ inputs.action }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify dispatcher about execution
        if: ${{ inputs.channel }}
        run: |
          URL=$(gh api "/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs" -q ".jobs[0].html_url")
          curl https://patchbay.pub/pubsub/$CHANNEL -d "$URL"
        env:
          CHANNEL: ${{ inputs.channel }}
          GH_TOKEN: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          path: scripts
      - uses: actions/checkout@v3
        with:
          repository: vd-plugins/proxy
          token: ${{ secrets.PROXY_TOKEN }}
          path: proxy

      - name: Execute script
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cd proxy
          node ../scripts/$ACTION.mjs
          git push
        env:
          ACTION: ${{ inputs.action }}
          PLUGINS: ${{ inputs.plugins }}
